# Numpy vs. list
(pip install numpy pandas matplotlib)
- 벡터 연산
- 크기 변경
- 데이터 타입
- 메모리 효율성 >> 연산 속도

In [1]:
import numpy as np

- array 는 생성한 뒤, 값을 추가할 수 없다(변경가능)
- array는 벡터연산이 가능하다

- list 는 생성, 삭제, 변경 모두 가능

In [26]:
list_1 = [0,1,2,3,4]

# for idx, i in enumerate(list_1):
    # print(f'{idx = }, {i = }')
    # list_1[idx] = i + 1
list_2 = []
for i in list_1:
    res = i + 1
    list_2.append(res)

print(f'{list_1 = }')
# print(f'{list_2 = }')

arr_1 = np.array(list_1)

arr_2 = arr_1 + 1

print(f'{arr_1 = }')
print(f'{arr_2 = }')

list_1 = [1, 2, 3, 4, 5]


In [30]:
# list_1 = ["hello",'a',arr_2,3,1343.45]
list_1 = [0,1,2,3,4]
print(f'{list_1 = }')

arr_1 = np.array(list_1)

list_1 = [0, 1, 2, 3, 4]


In [46]:
# 다양한 차원의 array
list2 = [[0,1,2], [3,4.3,5], [6,7,8]]
arr2d = np.array(list2, dtype='int')

print(list2)
print(arr2d)

arr2d = arr2d.astype('int')
print(arr2d)

arr2d.tolist()

[[0, 1, 2], [3, 4.3, 5], [6, 7, 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

# Create a numpy array

# 벡터 연산

# 크기 변경

# 데이터 타입

# numpy array 연산

# numpy 고급

In [58]:
print(arr2d)
print(arr2d.shape)


print(arr2d[:2, :2])

[[1 2 3 4]
 [3 4 5 6]
 [5 6 7 7]]
(3, 4)
[[1 2]
 [3 4]]


In [60]:
arr3 = arr2d > 4
print(arr3)

arr2d[arr3]

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


array([5, 6, 5, 6, 7, 7])

# mean, min, max, std

In [64]:
print(arr2d)

print(f'{arr2d.mean() = }')
print(f'{arr2d.max() = }')
print(f'{arr2d.min() = }')
print(f'{arr2d.std() = }')

[[1 2 3 4]
 [3 4 5 6]
 [5 6 7 7]]
arr2d.mean() = 4.416666666666667
arr2d.max() = 7
arr2d.min() = 1
arr2d.std() = 1.846543317180028


# 배열의 shape 변경

In [75]:
print(arr2d.shape)
# print(arr2d.reshape(1,12).shape)
# print(np.array([1,2,3,4,5,6,7,8,9,10,11,12]).shape)


(3, 4)


In [85]:
# array => 1차원 평면화: flatten(), ravel()
list_2 = [[1,2,3,4], [3,4,5,6], [5,6,7,7]]
arr2d = np.array(list_2)
print(f'{arr2d = }')

b1 = arr2d.flatten()
print(f'{b1 = }')
b1[0] = 100
print(f'{b1 = }')

print(f'{arr2d = }')

arr2d = array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 6, 7, 7]])
b1 = array([1, 2, 3, 4, 3, 4, 5, 6, 5, 6, 7, 7])
b1 = array([100,   2,   3,   4,   3,   4,   5,   6,   5,   6,   7,   7])
arr2d = array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [5, 6, 7, 7]])


In [86]:
b2 = arr2d.ravel()
print(f'{b2 = }')
b2[0] = 100

print(f'{b2 = }')
print(f'{arr2d = }')

b2 = array([1, 2, 3, 4, 3, 4, 5, 6, 5, 6, 7, 7])
b2 = array([100,   2,   3,   4,   3,   4,   5,   6,   5,   6,   7,   7])
arr2d = array([[100,   2,   3,   4],
       [  3,   4,   5,   6],
       [  5,   6,   7,   7]])


In [94]:
# Lower limit is 0 be default : 0 to 9
# np.arange(10)

# 0 to 9 with step of 2
# np.arange(0, 10, 2)

# 10 to 1, decreasing order
# np.arange(10, 0, -1)

a = np.linspace(start=1, stop=50, num=10, dtype='int').tolist()



[1, 6, 11, 17, 22, 28, 33, 39, 44, 50]

# Random Numbers

# 

In [113]:
print(np.random.rand(5)) # [0, 1]

print(np.random.randn(5)) # normal distribution, mean=0, variance= 1

# pick 2 items from a give population
print(f'{a = }')

np.random.choice(a, size=2) # size means the number of picks



[0.16241372 0.10684655 0.91683611 0.73978567 0.38670889]
[-0.6769938   1.34907955  0.94006575  0.04313695 -0.94017787]
a = [1, 6, 11, 17, 22, 28, 33, 39, 44, 50]


array([11, 33])

# 샘플 추출을 반복할 때 동일한 결과를 보장하기 위한 방법

In [130]:
# Random seed

np.random.seed(1234)

print(np.random.rand(5)) # [0, 1]
print(np.random.randn(5)) # normal distribution, mean=0, variance= 1
# pick 2 items from a give population
print(f'{a = }')
np.random.choice(a, size=2) # size means the number of picks


[0.19151945 0.62210877 0.43772774 0.78535858 0.77997581]
[-0.94029827 -0.95658428 -0.33060682  0.87412791  2.00254961]
a = [1, 6, 11, 17, 22, 28, 33, 39, 44, 50]


array([50, 33])

In [144]:
np.random.seed(49)

a = np.random.randint(0, 10, size=5)
print(f'{a = }, shape = {a.shape}')

# np.where(a > 5, 'gt5', 'le5')

a = array([8, 5, 6, 4, 2]), shape = (5,)
